In [163]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [164]:
file_path = 'C:\\Users\\amuthumanikandan\\PycharmProjects\\Meachine Learning\\Ageweight.csv'
df = pd.read_csv(file_path)
df.head(10)


Height  Weight
0     150      45
1     160      50
2     170      55
3     180      60
4     190      65
5     200      70

In [165]:
# df['Height'] = pd.to_numeric(df['Height'], errors='coerce')
# df['Weight'] = pd.to_numeric(df['Height'], errors='coerce')

In [166]:
df.columns

Index(['Height', 'Weight'], dtype='object')

In [167]:
X = df['Height']
y = df['Weight']
X = np.array(X).reshape(-1,1)
y = np.array(y).reshape(-1,1)

In [168]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
  X,y , random_state=104,test_size=0.2, shuffle=True)

In [169]:
# print("X Train:")
# print(X_train.head())
# print(X_train.shape)

X_train

array([[170],
       [190],
       [160],
       [200]])

In [170]:
# print('')
# print('X_test : ')
# print(X_test.head())
# print(X_test.shape)

In [171]:
# print('')
# print('y_train : ')
# print(y_train.head())
# print(y_train.shape)

In [172]:

# print('')
# print('y_test : ')
# print(y_test.info)
# print(y_test.shape)

In [173]:

X_train

array([[170],
       [190],
       [160],
       [200]])

In [174]:
# print("X_train types:\n", X_train.dtypes)
# print("y_train type:\n", y_train.dtype)

# # Check for missing values
# #print("Missing values in X_train:\n", X_train.isnull().sum())
# #print("Missing values in y_train:\n", y_train.isnull().sum())

X_train

array([[170],
       [190],
       [160],
       [200]])

In [175]:
# Example of converting categorical columns (if any)
#X_train = pd.get_dummies(X_train, drop_first=True)
#X_test = pd.get_dummies(X_test, drop_first=True)


In [176]:
# Drop rows with missing values
#X_train = X_train.dropna()
#y_train = y_train.dropna()

# Or fill missing values with the mean or other value
#X_train = X_train.fillna(X_train.mean())
#y_train = y_train.fillna(y_train.mean())

In [177]:
X_train

print(df.dtypes)

df = df.apply(pd.to_numeric, errors='coerce')


Height    int64
Weight    int64
dtype: object


In [178]:
print(df.dtypes)

Height    int64
Weight    int64
dtype: object


In [179]:
X_train

array([[170],
       [190],
       [160],
       [200]])

In [180]:
y_train

array([[55],
       [65],
       [50],
       [70]])

In [181]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm.fit(X_train, y_train)
print("Intercept:", lm.intercept_)
print("Coefficient:", lm.coef_)

Intercept: [-30.]
Coefficient: [[0.5]]


In [182]:
print(lm.intercept_)


[-30.]


In [183]:
lm.coef_


array([[0.5]])

In [187]:
predictions = lm.predict(X_test)
predictions

array([[60.],
       [45.]])

In [184]:
# cdf = pd.DataFrame(lm.coef_,X.columns,columns=['Coeff'])
# cdf